### PR TITLE
Wait for xapi to be up before making XenAPI calls

### LINKED ISSUE #19: Fails to communicate with xapi at startup
From https://github.com/xapi-project/xapi-nbd/pull/18 :

When I rebooted the machine, I got `ECONNREFUSED`, probably when `xapi-nbd` tried to connect to xapi's Unix domain socket:
```
Sep 28 18:30:33 localhost xapi-nbd[2843]: Caught: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 18:30:33 localhost xapi-nbd[2843]: main: Caught unexpected exception: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 18:30:33 localhost xapi-nbd[2843]: xapi-nbd: internal error, uncaught exception:
Sep 28 18:30:33 localhost xapi-nbd[2843]: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 18:30:33 localhost xapi-nbd[2843]: Raised at file "src/core/lwt.ml", line 805, characters 16-23
Sep 28 18:30:33 localhost xapi-nbd[2843]: Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Sep 28 18:30:33 localhost xapi-nbd[2843]: Called from file "src/main.ml", line 135, characters 2-181
Sep 28 18:30:33 localhost xapi-nbd[2843]: Called from file "src/cmdliner_term.ml", line 27, characters 19-24
Sep 28 18:30:33 localhost xapi-nbd[2843]: Called from file "src/cmdliner.ml", line 27, characters 27-34
Sep 28 18:30:33 localhost xapi-nbd[2843]: Called from file "src/cmdliner.ml", line 106, characters 32-39
Sep 28 18:30:33 localhost systemd[1]: xapi-nbd.service: main process exited, code=exited, status=1/FAILURE
Sep 28 18:30:33 localhost systemd[1]: Unit xapi-nbd.service entered failed state.
Sep 28 18:30:33 localhost systemd[1]: xapi-nbd.service failed.
Sep 28 18:30:34 localhost systemd[1]: xapi-nbd.service holdoff time over, scheduling restart.
```
When I started it manually later, it worked, and it cleaned up the leaked VDIs properly.
This issue happens consistently at startup: the NBD server will try to make XenAPI calls via the Unix domain socket and will fail.

Even if we make the server path-activated by both the unix domain socket of xapi and the `.pem` file, there are still transient errors:
```
Sep 28 21:42:41 localhost xapi-nbd[2605]: Caught: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 21:42:41 localhost xapi-nbd[2605]: main: Caught unexpected exception: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 21:42:41 localhost xapi-nbd[2605]: xapi-nbd: internal error, uncaught exception:
Sep 28 21:42:41 localhost xapi-nbd[2605]: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 28 21:42:41 localhost xapi-nbd[2605]: Raised at file "src/core/lwt.ml", line 805, characters 16-23
Sep 28 21:42:41 localhost xapi-nbd[2605]: Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Sep 28 21:42:41 localhost xapi-nbd[2605]: Called from file "src/main.ml", line 135, characters 2-181
Sep 28 21:42:41 localhost xapi-nbd[2605]: Called from file "src/cmdliner_term.ml", line 27, characters 19-24
Sep 28 21:42:41 localhost xapi-nbd[2605]: Called from file "src/cmdliner.ml", line 27, characters 27-34
Sep 28 21:42:41 localhost xapi-nbd[2605]: Called from file "src/cmdliner.ml", line 106, characters 32-39
Sep 28 21:42:41 localhost systemd[1]: xapi-nbd.service: main process exited, code=exited, status=1/FAILURE
Sep 28 21:42:41 localhost systemd[1]: Unit xapi-nbd.service entered failed state.
Sep 28 21:42:41 localhost systemd[1]: xapi-nbd.service failed.
Sep 28 21:42:41 localhost systemd[1]: xapi-nbd.service holdoff time over, scheduling restart.
Sep 28 21:42:41 localhost systemd[1]: Cannot add dependency job for unit lvm2-activation.service, ignoring: Unit lvm2-activation.service is masked.
Sep 28 21:42:41 localhost systemd[1]: Cannot add dependency job for unit lvm2-activation-early.service, ignoring: Unit lvm2-activation-early.service is
masked.
Sep 28 21:42:41 localhost systemd[1]: start request repeated too quickly for xapi-nbd.service
Sep 28 21:42:41 localhost systemd[1]: Failed to start NBD server that exposes XenServer disks.
Sep 28 21:42:41 localhost systemd[1]: Unit xapi-nbd.service entered failed state.
Sep 28 21:42:41 localhost systemd[1]: xapi-nbd.service failed.
Sep 28 21:42:41 localhost ntpd[2475]: 0.0.0.0 c615 05 clock_sync
Sep 28 21:42:45 localhost systemd[1]: Cannot add dependency job for unit lvm2-activation.service, ignoring: Unit lvm2-activation.service is masked.
Sep 28 21:42:45 localhost systemd[1]: Cannot add dependency job for unit lvm2-activation-early.service, ignoring: Unit lvm2-activation-early.service is
masked.
Sep 28 21:42:45 localhost systemd[1]: Started NBD server that exposes XenServer disks.
Sep 28 21:42:45 localhost systemd[1]: Starting NBD server that exposes XenServer disks...
Sep 28 21:42:45 localhost xapi-nbd[2778]: main: Starting xapi-nbd: port = '10809'; certfile = '/etc/xensource/xapi-ssl.pem'; ciphersuites = '!EXPORT:RSA
+AES128-SHA256' no_tls = 'false'
Sep 28 21:42:46 localhost xapi-nbd[2778]: main: Caught unexpected exception: Server_error(INTERNAL_ERROR, [ missing table; host;  ])
Sep 28 21:42:46 localhost xapi-nbd[2778]: xapi-nbd: internal error, uncaught exception:
Sep 28 21:42:46 localhost xapi-nbd[2778]: Server_error(INTERNAL_ERROR, [ missing table; host;  ])
Sep 28 21:42:46 localhost xapi-nbd[2778]: Raised at file "src/core/lwt.ml", line 805, characters 16-23
Sep 28 21:42:46 localhost xapi-nbd[2778]: Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Sep 28 21:42:46 localhost xapi-nbd[2778]: Called from file "src/main.ml", line 135, characters 2-181
Sep 28 21:42:46 localhost xapi-nbd[2778]: Called from file "src/cmdliner_term.ml", line 27, characters 19-24
Sep 28 21:42:46 localhost xapi-nbd[2778]: Called from file "src/cmdliner.ml", line 27, characters 27-34
Sep 28 21:42:46 localhost xapi-nbd[2778]: Called from file "src/cmdliner.ml", line 106, characters 32-39
Sep 28 21:42:46 localhost systemd[1]: xapi-nbd.service: main process exited, code=exited, status=1/FAILURE
Sep 28 21:42:46 localhost systemd[1]: Unit xapi-nbd.service entered failed state.
Sep 28 21:42:46 localhost systemd[1]: xapi-nbd.service failed.
Sep 28 21:42:46 localhost systemd[1]: xapi-nbd.service holdoff time over, scheduling restart.
Sep 28 21:42:46 localhost systemd[1]: Started NBD server that exposes XenServer disks.
Sep 28 21:42:46 localhost systemd[1]: Starting NBD server that exposes XenServer disks...
Sep 28 21:42:46 localhost xapi-nbd[2805]: main: Starting xapi-nbd: port = '10809'; certfile = '/etc/xensource/xapi-ssl.pem'; ciphersuites = '!EXPORT:RSA+AES128-SHA256' no_tls = 'false'
Sep 28 21:42:46 localhost xapi-nbd[2805]: main: Checking if there are any VBDs to clean up that leaked during the previous run
Sep 28 21:42:46 localhost xapi-nbd[2805]: main: Initialising TLS
Sep 28 21:42:46 localhost xapi-nbd[2805]: main: Setting up server socket
Sep 28 21:42:46 localhost xapi-nbd[2805]: main: Listening for incoming connections
```
So it seems that xapi is not yet completely ready when its Unix domain socket is created (`Sep 28 21:42:46 localhost xapi-nbd[2778]: Server_error(INTERNAL_ERROR, [ missing table; host;  ])`). So I'll just add a loop to the startup of xapi-nbd that will try logging in until it succeeds, up to a timeout, to ensure that xapi is up when we need it.

### PR DESCRIPTION
**Pull request by gaborigloi**
Previously when the server tried to login at startup, it failed
immediately because xapi wasn't ready yet, even though systemd starts
xapi-nbd after xapi. The proper long term fix will be for xapi to notify
systemd when its startup sequence has completed, and when that is done,
this temporary fix can be removed.

Waiting for xapi's Unix domain socket to be up does not work, there
would still be transient failures because apparently xapi is not
completely ready when the Unix domain socket is created.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

Fixes #19

### CODE REVIEW

**Comment by gaborigloi** [comment]
I've tested it, and now it does not fail during startup:
```
Sep 29 14:45:27 localhost xapi-nbd[2434]: main: Starting xapi-nbd: port = '10809'; certfile = '/etc/xensource/xapi-ssl.pem'; ciphersuites = '!EXPORT:RSA+AES128-SHA256' no_tls = 'false'
Sep 29 14:45:27 localhost xapi-nbd[2434]: main: Trying to log in via xapi's Unix domain socket for 120.000000 seconds
Sep 29 14:45:27 localhost xapi-nbd[2434]: Caught: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 29 14:45:27 localhost xapi-nbd[2434]: main: Failed to log in via xapi's Unix domain socket: Unix.Unix_error(Unix.ECONNREFUSED, "connect", ""); retrying in 4.000000 seconds
Sep 29 14:45:31 localhost xapi-nbd[2434]: Caught: Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
Sep 29 14:45:31 localhost xapi-nbd[2434]: main: Failed to log in via xapi's Unix domain socket: Unix.Unix_error(Unix.ECONNREFUSED, "connect", ""); retrying in 4.000000 seconds
Sep 29 14:45:35 localhost xapi-nbd[2434]: main: Checking if there are any VBDs to clean up that leaked during the previous run
Sep 29 14:45:35 localhost xapi-nbd[2434]: main: Initialising TLS
Sep 29 14:45:35 localhost xapi-nbd[2434]: main: Setting up server socket
Sep 29 14:45:35 localhost xapi-nbd[2434]: main: Listening for incoming connections
```

File: src/cleanup.ml [hunk 1]
```diff
@@ -2,17 +2,50 @@ open Lwt.Infix
...
+module Local_xapi_session = struct
+  let wait_for_xapi_and_login () =
+    let rpc = Xen_api.make Consts.xapi_unix_domain_socket_uri in
+    let rec loop () =
+      Lwt.catch
+        (fun () -> Xen_api.Session.login_with_password ~rpc ~uname:"" ~pwd:"" ~version:"1.0" ~originator:"xapi-nbd")
+        (fun e ->
+           Lwt_log.warning_f "Failed to log in via xapi's Unix domain socket: %s; retrying in %f seconds" (Printexc.to_string e) Consts.wait_for_xapi_retry_delay_seconds >>= fun () ->
+           Lwt_unix.sleep Consts.wait_for_xapi_retry_delay_seconds >>= fun () ->
+           loop ()
```
Comment (mseri) [inline src/cleanup.ml:14]: What about limiting the number of retries as well?

Comment (gaborigloi) [reply src/cleanup.ml:14]: Hmm, so you reckon that's also necessary in addition to the timeout? :thinking:

Comment (mseri) [reply src/cleanup.ml:14]: I don't know. I was asking for your opinion. Is it worth trying forever or we should back out and fail after few minutes of attempts?

File: src/cleanup.ml [hunk 2]
```diff
@@ -175,6 +207,5 @@ end
 
 module Persistent = struct
   let cleanup () =
-    local_login () >>= fun (rpc, session_id) ->
-    VBD.Persistent.cleanup rpc session_id
+    Local_xapi_session.with_session VBD.Persistent.cleanup
```
Comment (gaborigloi) [inline src/cleanup.ml:210]: I could also change the code to only log in when the list of VBDs/block devices to clean up is non-empty, but thought it's better to keep cleanup code clean and simple, because this has to work.

File: src/cleanup.ml (hunk 1 above)
Comment (gaborigloi) [reply src/cleanup.ml:14]: Actually, the number of retries is limited because we have a timeout below, which is 120 seconds, and we retry every 4 seconds, so the max no of retries is 30.

Comment (mseri) [reply src/cleanup.ml:14]: Yes, it was more about doing one or the other. As we discussed let's leave it as it is but increase the overall timeout to `300.0`

Comment (gaborigloi) [reply src/cleanup.ml:14]: Done - now the timeout is `300` seconds.

File: src/cleanup.ml [hunk 3]
```diff
@@ -2,17 +2,50 @@ open Lwt.Infix
...
+      let msg = Printf.sprintf "Failed to log in via xapi's Unix domain socket in %f seconds" timeout_s in
+      Lwt_log.fatal msg >>= fun () ->
+      Lwt.fail_with msg
+    in
 
-let local_login () =
-  let rpc = Xen_api.make Consts.xapi_unix_domain_socket_uri in
-  Xen_api.Session.login_with_password ~rpc ~uname:"" ~pwd:"" ~version:"1.0" ~originator:"xapi-nbd" >|= fun session_id ->
-  (rpc, session_id)
+    Lwt_log.notice_f "Trying to log in via xapi's Unix domain socket for %f seconds" Consts.wait_for_xapi_timeout_seconds >>= fun () ->
```
Comment (mseri) [inline src/cleanup.ml]: Change it from `trying to log` to `will try to log`

**Review by mseri — APPROVED** [review]

**Comment by gaborigloi** [comment]
Thanks a lot for the review! :smile: Merging as I've built it locally.

File: src/cleanup.ml (hunk 1 above)
Comment (euanh) [reply src/cleanup.ml:14]: In general it's a bad idea to retry forever.   Having software just "hang" is very frustrating for the user.  Once it is clear that something isn't going to work you should stop retrying and escalate the problem to the next level of process management logic until eventually the user gets a message.
